using System;
using System.Globalization;
using System.Web.Security;
using System.Web.UI.WebControls;
using GalleryServerPro.Business;
using GalleryServerPro.Business.Interfaces;
using GalleryServerPro.ErrorHandler.CustomExceptions;

namespace GalleryServerPro.Web.gs.pages.admin
{
	public partial class general : Pages.AdminPage
	{
		#region Private Fields

		private bool? _isInTrialPeriod;
		private bool? _isRegistered;
		private string _messageText;
		private string _messageCssClass;
		private bool _messageIsError;

		#endregion

		#region Properties

		public bool IsInTrialPeriod
		{
			get
			{
				if (!this._isInTrialPeriod.HasValue)
				{
					this._isInTrialPeriod = AppSetting.Instance.IsInTrialPeriod;
				}
				return _isInTrialPeriod.Value;
			}
			set { _isInTrialPeriod = value; }
		}

		public bool IsRegistered
		{
			get
			{
				if (!this._isRegistered.HasValue)
				{
					this._isRegistered = AppSetting.Instance.IsRegistered;
				}
				return _isRegistered.Value;
			}
			set { _isRegistered = value; }
		}

		public string MessageText
		{
			get { return _messageText; }
			set { _messageText = value; }
		}

		public string MessageCssClass
		{
			get { return _messageCssClass; }
			set { _messageCssClass = value; }
		}

		public bool MessageIsError
		{
			get { return _messageIsError; }
			set { _messageIsError = value; }
		}

		public bool SavingIsEnabled
		{
			get
			{
				return (HasEditConfigPermission && (this.IsInTrialPeriod || this.IsRegistered));
			}
		}

		public System.Configuration.Provider.ProviderBase MembershipGsp
		{
			get
			{
				return Controller.UserController.MembershipGsp;
			}
		}

		public System.Configuration.Provider.ProviderBase RoleGsp
		{
			get
			{
				return Controller.RoleController.RoleGsp;
			}
		}

		public System.Configuration.Provider.ProviderBase ProfileGsp
		{
			get
			{
				return System.Web.Profile.ProfileManager.Provider;
			}
		}

		public System.Configuration.Provider.ProviderBase GalleryDataProvider
		{
			get
			{
				return (System.Configuration.Provider.ProviderBase)Factory.GetDataProvider();
			}
		}

		#endregion

		#region Protected Events

		protected void Page_Init(object sender, EventArgs e)
		{
			this.AdminHeaderPlaceHolder = phAdminHeader;
			this.AdminFooterPlaceHolder = phAdminFooter;
		}

		protected void Page_Load(object sender, EventArgs e)
		{
			this.CheckUserSecurity(SecurityActions.AdministerSite);

			if (!IsPostBack)
			{
				ConfigureControls();
			}

			ConfigureControlsEveryTime();
		}

		protected void btnEnterProductKey_Click(object sender, EventArgs args)
		{
			SaveProductKey();
		}

		protected override bool OnBubbleEvent(object source, EventArgs args)
		{
			//An event from the control has bubbled up.  If it's the Ok button, then run the
			//code to save the data to the database; otherwise ignore.
			Button btn = source as Button;
			if ((btn != null) && (((btn.ID == "btnOkTop") || (btn.ID == "btnOkBottom"))))
			{
				SaveSettings();
			}

			return true;
		}

		protected void btnThrowError_Click(object sender, EventArgs e)
		{
			throw new WebException("This is a test error generated by Gallery Server Pro.");
		}

		#endregion

		#region Private Methods

		private void ConfigureControls()
		{
			AdminPageTitle = Resources.GalleryServerPro.Admin_Site_Settings_General_Page_Header;
			txtProductKey.Text = Web.Config.GetCore().ProductKey;

			OkButtonBottom.Enabled = this.SavingIsEnabled;
			OkButtonTop.Enabled = this.SavingIsEnabled;

			this.wwDataBinder.DataBind();

			DetermineMessage();

			UpdateUI();

			UpdateProductKeyValidationMessage();

		}

		private void ConfigureControlsEveryTime()
		{
			this.PageTitle = Resources.GalleryServerPro.Admin_Site_Settings_General_Page_Header;

			lblEmailAttn.Text = String.Format(Resources.GalleryServerPro.Admin_Email_SendEmail_Attn_Label, Util.GetUrl(PageId.admin_email));

			lblVersion.Text = String.Concat("v", Util.GetGalleryServerVersion());

			chkEnableExceptionHandler.Attributes["onchange"] = "updateDisplayDetailErrorCheckbox();";
		}

		private void DetermineMessage()
		{
			if (!HasEditConfigPermission)
			{
				this.MessageText = String.Format(Resources.GalleryServerPro.Admin_Config_Security_Ex_Msg, Util.GalleryServerProConfigFilePath);
				this.MessageCssClass = "wwErrorSuccess gsp_msgwarning";

				OkButtonBottom.Enabled = false;
				OkButtonTop.Enabled = false;

				foreach (System.Web.UI.Control ctl in this.Controls)
				{
					if ((ctl is CheckBox) || (ctl is TextBox) || (ctl is DropDownList))
					{
						if (ctl != txtProductKey)
						{
							((WebControl)ctl).Enabled = false;
						}
					}
				}
			}

			bool isInTrialMode = (this.IsInTrialPeriod && !this.IsRegistered);
			if (isInTrialMode)
			{
				IGallery gallery = Factory.GetDataProvider().Gallery_GetCurrentGallery(new Business.Gallery());
				int daysLeftInTrial = (gallery.CreationDate.AddDays(GlobalConstants.TrialNumberOfDays) - DateTime.Today).Days;
				this.MessageText = string.Format(CultureInfo.CurrentCulture, Resources.GalleryServerPro.Admin_In_Trial_Period_Msg, daysLeftInTrial);
				this.MessageCssClass = "wwErrorSuccess gsp_msgfriendly";
			}

			bool trialPeriodExpired = (!this.IsInTrialPeriod && !this.IsRegistered);
			if (trialPeriodExpired)
			{
				this.MessageText = Resources.GalleryServerPro.Admin_Need_Product_Key_Msg;
				this.MessageCssClass = "wwErrorSuccess gsp_msgwarning";
			}
		}

		private void UpdateUI()
		{
			if (!String.IsNullOrEmpty(this.MessageText))
			{
				wwMessage.CssClass = this.MessageCssClass;

				if (this.MessageIsError)
					wwMessage.Text = this.MessageText;
				else
					wwMessage.ShowMessage(this.MessageText);
			}
		}

		private void UpdateProductKeyValidationMessage()
		{
			string productKey = txtProductKey.Text;

			if (String.IsNullOrEmpty(productKey))
			{
				lblProductKeyValidationMsg.Text = Resources.GalleryServerPro.Admin_Default_ProductKey_NotEntered_Label;
				lblProductKeyValidationMsg.CssClass = "gsp_msgfriendly";
				imgProductKeyValidation.ImageUrl = Util.GetUrl("/images/info.gif");
				imgProductKeyValidation.Visible = true;
			}
			else if (GlobalConstants.ProductKey.Equals(txtProductKey.Text))
			{
				lblProductKeyValidationMsg.Text = Resources.GalleryServerPro.Admin_Default_ProductKey_Correct_Label;
				lblProductKeyValidationMsg.CssClass = "gsp_msgfriendly";
				imgProductKeyValidation.ImageUrl = Util.GetUrl("/images/ok_16x16.png");
				imgProductKeyValidation.Visible = true;
			}
			else
			{
				lblProductKeyValidationMsg.Text = Resources.GalleryServerPro.Admin_Default_ProductKey_Incorrect_Label;
				lblProductKeyValidationMsg.CssClass = "gsp_msgwarning";
				imgProductKeyValidation.ImageUrl = Util.GetUrl("/images/error_16x16.png");
				imgProductKeyValidation.Visible = true;
			}
		}

		private void SaveProductKey()
		{
			string productKey = txtProductKey.Text;

			if ((!String.IsNullOrEmpty(productKey)) && !GlobalConstants.ProductKey.Equals(txtProductKey.Text))
				wwDataBinder.AddBindingError(Resources.GalleryServerPro.Admin_Default_ProductKey_Incorrect_Msg, txtProductKey);

			if (wwDataBinder.BindingErrors.Count > 0)
			{
				this.MessageText = wwDataBinder.BindingErrors.ToHtml();
				this.MessageCssClass = "wwErrorFailure gsp_msgwarning";
				this.MessageIsError = true;
				UpdateUI();
				UpdateProductKeyValidationMessage();
				return;
			}

			CoreConfig.productKey = productKey;

			Controller.GspConfigController.SaveCore(this.CoreConfig);

			if (String.IsNullOrEmpty(productKey))
			{
				this.IsRegistered = false;
				DetermineMessage();
			}
			else
			{
				this.IsRegistered = true;
				this.MessageText = Resources.GalleryServerPro.Admin_Save_ProductKey_Success_Text;
				this.MessageCssClass = "wwErrorSuccess gsp_msgfriendly gsp_bold";
			}

			// Enable or disable the Save buttons
			OkButtonBottom.Enabled = this.SavingIsEnabled;
			OkButtonTop.Enabled = this.SavingIsEnabled;
				
			UpdateUI();
			UpdateProductKeyValidationMessage();
		}

		private void SaveSettings()
		{
			this.wwDataBinder.Unbind(this);

			if (wwDataBinder.BindingErrors.Count > 0)
			{
				this.MessageText = wwDataBinder.BindingErrors.ToHtml();
				this.MessageCssClass = "wwErrorFailure gsp_msgwarning";
				this.MessageIsError = true;
				UpdateUI();
				return;
			}

			Controller.GspConfigController.SaveCore(this.CoreConfig);

			this.MessageText = Resources.GalleryServerPro.Admin_Save_Success_With_Refresh_Note_Text;
			this.MessageCssClass = "wwErrorSuccess gsp_msgfriendly gsp_bold";
			
			UpdateUI();
		}

		#endregion
	}
}